apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  PG_USER: {{ .Values.secrets.pgUser | b64enc }}
  PG_PASSWORD: {{ .Values.secrets.pgPassword | b64enc }}
  POSTGRES_USER: {{ .Values.secrets.pgUser | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secrets.pgPassword | b64enc }}
  RABBITMQ_USER: {{ .Values.secrets.rabbitmqUser | b64enc }}
  RABBITMQ_PASS: {{ .Values.secrets.rabbitmqPass | b64enc }}
  RABBITMQ_ERLANG_COOKIE: {{ .Values.secrets.rabbitmqErlangCookie | b64enc }}
  MINIO_ACCESS_KEY: {{ .Values.secrets.minioAccessKey | b64enc }}
  MINIO_SECRET_KEY: {{ .Values.secrets.minioSecretKey | b64enc }}

