apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streaming-service
  template:
    metadata:
      labels:
        app: streaming-service
    spec:
      containers:
        - name: streaming-service
          image: video-streaming-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          command: ["/bin/sh", "-c"]
          args:
            - >
              mvn -pl streaming-service -DskipTests exec:java
              -Dexec.mainClass=com.distributed26.videostreaming.streaming.streaming.StreamingServiceApplication
          envFrom:
            - configMapRef:
                name: video-streaming-config
            - secretRef:
                name: video-streaming-secrets
          startupProbe:
            httpGet:
              path: /health
              port: 8083
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
